### ISSUE TITLE
Raumtemperatur per Modbus Register

### ISSUE THREAD

**Issue by WolfWalter** [saruter/smarthome#1]
Hallo,
mein Kollege aus dem Solvis-Kundendienst hat mich auf ihre Anfrage zum setzen der Raumtemperatur per Modbus hingewiesen.

Damit der Werte per Modbus gesetzt werden kann, muss der Heizkreis mit Raumbediengerät initialisiert werden. Um die Temperatur per Modbus vorgeben zu können, kann man in der SC2 unter Installateur>Sonstiges>Remote>Seite 3 die Temperatur für den HK auf "Modbus" umstellen. Auf der Seite 2 muss der Modus auf "schreiben" stehen.

Um das Raumbediengerät zu aktivieren ist es eigentlich notwendig die Werkseinstellungen zu laden. Alternativ könnte man dafür die [Solvis ParameterApp]( https://www.solvis.de/solvisparameter-app/) nutzen.

Schöne Grüße

Wolf Walter

**Comment by saruter** [comment]
@WolfWalter 
Hallo,
vielen Dank für Ihre Infos. Das waren genau die Punkte die mir zur Realisierung gefehlt haben. Ich hatte bereits vermutet, dass ich die Werkseinstellungen laden muss, mich davor aber noch gescheut ohne genau zu wissen was anschließend noch zu tun ist. Aber nach genauer Dokumentation aller Parameter habe ich es durchgeführt und das schreiben der Raumtemperatur in das  Modbus-Register funktioniert nun. 
Wie ich bemerkt habe, muss der aktuelle Temperaturwert ca. alle 60 Sekunden geschrieben werden, sonst zeigt die SC2 nur noch "--" als Raumtemperatur an, was aber auch kein Hindernis ist.

Meine Doku zur Heizungssteuerung habe ich ebenfalls aktualisiert.

**Comment by EddyDsSmartHome** [comment]
> Hallo, mein Kollege aus dem Solvis-Kundendienst hat mich auf ihre Anfrage zum setzen der Raumtemperatur per Modbus hingewiesen.
> 
> Damit der Werte per Modbus gesetzt werden kann, muss der Heizkreis mit Raumbediengerät initialisiert werden. Um die Temperatur per Modbus vorgeben zu können, kann man in der SC2 unter Installateur>Sonstiges>Remote>Seite 3 die Temperatur für den HK auf "Modbus" umstellen. Auf der Seite 2 muss der Modus auf "schreiben" stehen.
> 
> Um das Raumbediengerät zu aktivieren ist es eigentlich notwendig die Werkseinstellungen zu laden. Alternativ könnte man dafür die [Solvis ParameterApp](https://www.solvis.de/solvisparameter-app/) nutzen.
> 
> Schöne Grüße
> 
> Wolf Walter
@WolfWalter 
Hi, ich weiß leider keine andere Möglichkeit wie dir hier zu schreiben und zu hoffen das du mir weiterhelfen kannst.
Über die Solvis Kontak Mail, habe ich bisher keine Antwort erhalten.
Ich möchte beim SolvisMax7 SC3 über den Modbus die Uhrzeiten für die Zirkulationspumpe ändern, diese sind aber wenn ich das richtig interpretiere irgendwie falsch hinterlegt (Bin Modbus technisch nicht sehr bewandert).
Die Register die für die Zirkulationspumpe hinterlegt sind, sind komplett falsch. Wenn ich per App die Uhrzeit für die Zirkulationspumpe ändere finde ich nur den Wert für Montag Start 1 und Start 0 auf Adresse 34174 und 34175. Alle anderen Werte finde ich in keiner Adresse wieder. Ich lasse mir alle anzeigen, aber bis auf die Warmwasser Aufbereitung Tag 1 bis Tag 7 passt ansonsten gar nichts mit der Doku. Könntest du bitte mit mir Kontakt aufnehmen, wie gesagt per Solvis Mail habe ich es schon 2 mal versucht, erste mal vor einigen Wochen, zweites mal vor 2 Tagen.
Mail: eddydssmarthome at gmail.com

**Comment by saruter** [comment]
> 
> Hi, ich weiß leider keine andere Möglichkeit wie dir hier zu schreiben und zu hoffen das du mir weiterhelfen kannst. Über die Solvis Kontak Mail, habe ich bisher keine Antwort erhalten. Ich möchte beim SolvisMax7 SC3 über den Modbus die Uhrzeiten für die Zirkulationspumpe ändern, diese sind aber wenn ich das richtig interpretiere irgendwie falsch hinterlegt (Bin Modbus technisch nicht sehr bewandert). Die Register die für die Zirkulationspumpe hinterlegt sind, sind komplett falsch. Wenn ich per App die Uhrzeit für die Zirkulationspumpe ändere finde ich nur den Wert für Montag Start 1 und Start 0 auf Adresse 34174 und 34175. Alle anderen Werte finde ich in keiner Adresse wieder. Ich lasse mir alle anzeigen, aber bis auf die Warmwasser Aufbereitung Tag 1 bis Tag 7 passt ansonsten gar nichts mit der Doku. Könntest du bitte mit mir Kontakt aufnehmen, wie gesagt per Solvis Mail habe ich es schon 2 mal versucht, erste mal vor einigen Wochen, zweites mal vor 2 Tagen. Mail: eddydssmarthome at gmail.com


Hallo @EddyDsSmartHome ,
ich habe das gerade mal bei mir ausprobiert und es sieht wirklich so aus, als wäre die Dokumentation zu den Modbus Registern falsch bzw. vertauscht. Wenn ich die Zeiten bei Warmwasser ändere, so ändern sich die Werte bei den Modbus Registern für "Wochenplan Zirk Tag x" und umgekehrt, wenn ich die Zeiten bei Zirkulation ändere, dann ändern sich die Werte bei den Registern für "Wochenplan WW Tag X". 
Ich habe die Werte mal jeweils am Dienstag geändert (immer Start/Stop 0) und die Werte änderten sich auch entsprechend in den Registern, nur halt gerade umgekehrt vertauscht (WW/Zirk).

Beispiel Dienstag Warmwasser Stop 0: 22:15 Uhr = "89" in Register 34223 (laut Doku Zirk Tag 2 Stop 0)

Also die Werte für die Wochentage scheinen übernommen zu werden, nur halt WW/Zirkulation vertauscht.

Hoffe, das hilft dir.

@WolfWalter : Evtl. könnten Sie bei Gelegenheit das o.g. Verhalten nachstellen und ggf. die Modbus Dokumentation auf der Solvis Homepage aktualisieren.

**Comment by EddyDsSmartHome** [comment]
Werde ich mir später nochmal anschauen. Ist dir auch aufgefallen das sich die Werte ab und zu mal ändern? Mir ist das bei mehreren Werten aufgefallen, das sie sich ändern. Bin gerade nicht zuhause und das rauszusuchen, aber das sollte eigentlich nicht möglich sein, das sich ein Wert ändert.

**Comment by EddyDsSmartHome** [comment]
> Hallo @EddyDsSmartHome , ich habe das gerade mal bei mir ausprobiert und es sieht wirklich so aus, als wäre die Dokumentation zu den Modbus Registern falsch bzw. vertauscht. Wenn ich die Zeiten bei Warmwasser ändere, so ändern sich die Werte bei den Modbus Registern für "Wochenplan Zirk Tag x" und umgekehrt, wenn ich die Zeiten bei Zirkulation ändere, dann ändern sich die Werte bei den Registern für "Wochenplan WW Tag X". Ich habe die Werte mal jeweils am Dienstag geändert (immer Start/Stop 0) und die Werte änderten sich auch entsprechend in den Registern, nur halt gerade umgekehrt vertauscht (WW/Zirk).
> 
> Beispiel Dienstag Warmwasser Stop 0: 22:15 Uhr = "89" in Register 34223 (laut Doku Zirk Tag 2 Stop 0)
> 
> Also die Werte für die Wochentage scheinen übernommen zu werden, nur halt WW/Zirkulation vertauscht.
> 
> Hoffe, das hilft dir.
> 
> @WolfWalter : Evtl. könnten Sie bei Gelegenheit das o.g. Verhalten nachstellen und ggf. die Modbus Dokumentation auf der Solvis Homepage aktualisieren.

@saruter 
Bin gerade zuhause und habe das mal getestet, also ab dem Register 34176 kommen keine sinnvolle Werte mehr rein.
34174 und 34174 sind Start/Stop Zirk Tag 1 und danach tauchen nur noch Werte die entweder 0 sind auf, oder 240,238,237,242,241. 
Das interessante ist, die Werte ändern sich auch alle paar Sekunden, was nicht sein sollte.
Im Unterschied zu dir habe ich SC3, laut deiner Website hast du SC2. Keine Ahnung in wieweit die zu vergleichen sind.
Habe mal dein Register getestet, aber ohne erfolg, der Wert wurde automatisch wieder auf 2xx gesetzt.
Ich habe auch mal alle Zeit-Fenster auf 0:00 gestellt (Warmwasser, Eco, SilentMode, Heizkreis) wenn ich dann bei Zirkulation z.B. Dienstag Start/Stop 1 im SolvisPortal  auf z.B. 6-7Uhr einstelle, finde ich nirgends den entsprechenden Wert, es wird weiterhin alles auf 0,240,238,237,242,241 angezeigt.
Siehe Bild: https://drive.google.com/file/d/1QCoXzKelmv54NXii_7PnWUi1ucRhlpJK/view?usp=sharing
Das selbe wenn ich die Uhrzeit bei WW im SolvisPortal einstelle, taucht die in keinem Register auf.
Da ich den ioBroker verwende und dort den Modbus Adapter, bin ich mir auch nicht sicher ob der richtig eingestellt ist. ABER der eine Wert kommt ja richtig rein (34174/34175) und kann auch geändert werden, das gleiche gilt für Register 2304(WW Modus),2305(WW Sollwert),2328(WW Nachheizung Start), die passen ja auch.
Ich habe absolut keine Ahnung mehr, mein Heizungsbauer ist da auch überfragt, das zählt nicht zu ihren normalen Aufgabe und Solvis selbst reagiert einfach nicht. Ich wollte einfach nur weg von den großen Hersteller und dachte nach den ganzen Berichten die ich gelesen habe, da machst du nichts falsch. Aber gar nicht auf Mails zu reagieren, nicht mal irgendwas wie "Ihre Mail wird bearbeitet, es kann paar Tage dauern" ... PUHHH bin mal gespannt wenn der erste Fehler auftaucht bei dem der Heizungsbauer nicht mehr weiter weiß, hoffe der hat einen guten Draht zu Solvis, ansonsten geht die gleiche Story weiter wie mit Viessmann.

**Comment by Antagor** [comment]
Hallo an alle Solvis-Besitzer,
ich habe eine SolvisMax mit SC2 ohne Remote und würde gerne die Daten direkt auslesen (nicht per SD-Karte).
Mehrfache Emails an Solvis mit der Bitte irgendwelche technischen Daten zu veröffentlichen wurden ignoriert.
Telefonisch bekommt man die unterschiedlichsten Auskünfte - aber alles nicht verwertbar.
Es heißt immer, das die Remote das Display NUR spiegelt, aber selbst dann einen Netzwerkanschluß incl. Modbus zur Verfügung stellt. 
Blöde Frage: Wenn per Modbus ein Register geändert werden soll "übersetzt" die Remote das für die SC2 in virtuelle Klicks auf den Bildschirm bis zur Einstellung?
Hat irgendjemand Infos was für Signale und/oder Protokolle an den "Netzwerkanschlüssen" der SC2 anliegen?
Kann man ev die auf der Platine bezeichnete RS232 Schnittstelle nutzen?
Ich sehe es nicht ein meine funktionierende SC2 gegen eine SC3 zu tauschen oder mir eine Remote zu kaufen, nur um die Daten lesen zu können - die müssen doch jetzt auch schon da sein..... es kommt doch nur auf das Protokoll an....
Ich würde mich freuen, wenn sich jemand findet und seine Informationen hier teilen würde.
Vielen Dank
