### ISSUE TITLE
Kurze Info?

### ISSUE THREAD

**Issue by tinkerberlin** [saruter/smarthome#12]
Hallo, ich habe gerade Deine Anleitung zum Ansteuern der Solvis Wärmepumpen über Modbus durchgelesen, da ich auch bald eine Solvis mein Eigen werde nennen dürfen...

Eine Frage nur hierzu: Du schreibst von der Einstellung der Raumsensoren, um damit die HK zu steuern (wenn ich's richtig gelesen habe). Ging es dabei darum, die Temperatur der einzelnen Räume zu steuern? Oder würdest Du eher die Durchschnittstemperatur aller Räume im Haus (bzw. die niedrigste Temperatur im Haus) nehmen und diese an die Solvis für einen einzigen "imaginären" HK geben, um so sicherzustellen, dass die Solvis das Wasser für die Heizungen trotz augenscheinlicher Wärme von draußen heizt?

Ich frage, weil ich eigentlich gedacht hatte die einzelnen Raum-Ventile für die Fußbodenheizung über "normale" Relais und Thermostat-Cards in Home Assistant ansteuern zu können. Im Prinzip muss dann die Solvis ja nur "heizen" wenn das Wasser im Tank zu kalt ist. 

Oder habe ich etwas falsch verstanden?

Vielen Dank für die Hilfe!!

**Comment by saruter** [comment]
Hi, ich habe nur einen Heizkreis und emuliere mit Home Assistant quasi den Temperatursensor der über das optionale Raumbedienelement eine Rückmeldung an die Solvis gibt wie warm es im Raum ist. Den Einfluss dieses Temperaturwertes auf die Vorlauftemperatur kann man dann im Menü des Heizkreises einstellen. Ich sende quasi per Modbus die Temperatur des Raums an die Steuerung statt per Raumbedienelement welches man sonst extra verkabeln müsste.
