### ISSUE TITLE
Solvis Remote doesn't connect to homeassistant

### ISSUE THREAD

**Issue by ThomasWollstadt** [saruter/smarthome#13]
Hello, I followed your documentation regarding the integration of SolvisMax into home assistant. I activated ModBus TCP in the Solvis System, Added your template into the configurations.yaml, updated IP address and restarted homeassistant.  Here the start section of the configuration .yaml 

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

modbus:
  - name: SolvisRemote
    type: tcp
    host: 192.168.178.54
    port: 502

    sensors:
      - name: Warmwasserpuffer
        unit_of_measurement: °C
        scale: 0.1
        slave: 1
        precision: 2
......

The overview layout of home assistant shows all sensors but each sensor is "not available". Seems like in general no conncection to the Solvis System ? Any advice how to test the connection?

**Comment by saruter** [comment]
Hi, when HA has problems connecting to a Modbus Device there should be logs indicating that under Settings --> System --> Logs like this or similar. 

```
Logger: homeassistant.components.modbus.modbus
Source: components/modbus/modbus.py:401
Integration: Modbus (documentation, issues)
First occurred: 3. Oktober 2023 um 16:15:01 (37 occurrences)
Last logged: 07:19:02

Pymodbus: SolvisRemote: Exception Response(134, 6, GatewayNoResponse)
Pymodbus: SolvisRemote: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 8 bytes (0 received)
```
