### ISSUE TITLE
Bitte um Kontaktaufnahme

### ISSUE THREAD

**Issue by garett13** [saruter/smarthome#2]
Hallo :) 
ich habe zu deinem Projekt "smarten" Stromzähler ein paar Fragen.. wäre es möglich, dass du mich mal kontaktierst?
Dauert auch wirklich nicht lange und würde mir sehr helfen.. 

yanki(at)gmx(punkt)de

Würde mich sehr freuen, da ich leider nicht weiterkomme und du bist auch der einzige, den ich mit so einem Projekt finde!

Danke dir vorab.
LG
René

**Comment by kotana** [comment]
Hallo ich würde mich auch freuen wenn du mich auch mal kurz kontaktierst.
Es geht um den Stromzähler
Ich weiß nicht ob bei mir alles richtig funktioniert.

Habe die selben Komponenten wie du benutzt.
Gruß Cata.

c.oprescu@web.de

**Comment by saruter** [comment]
Hallo kotana,

ich habe gerade die Doku zum Stromzähler etwas präzisiert. Der Fehler liegt im verwendeten Sensor als Quelle für die "utility_meter"-Integration in Home Assistant.

Der ESPHome Sensor "energieverbrauch_w" liefert die aktuelle (genauer gesagt in den letzten 60 Sekunden) errechnete Leistung die im Haus verbraucht wird. Der daraus abgeleitete ESPHome-Sensor "Tagesverbrauch" vom Typ "total_daily_energy" addiert diese Werte kontinuierlich in diesen Sensor, liefert also die Wh. Also die kommulierte verbrauchte Energie über die Zeit [Doku](https://esphome.io/components/sensor/total_daily_energy.htmll). Da dieser Sensor aber bei jedem Neustart des ESPs wieder auf Null gesetzt wird, wird in Home-Assistant über die Integration "utility_meter" die Werte dieses ESPHome Sensors "Tagesverbrauch, in Home Assistant als Sensor "sensor.tagesverbrauch" genannt, als Basis genutzt und hierüber dann die täglichen/wöchentlichen/jährlichen Daten gespeichert, und zwar persistent über jegliche Reboots des ESPs oder Home Assistant hinweg.

**Comment by kotana** [comment]
Hallo  saruter,

ich habe es mittlerweile hinbekommen.

![image](https://user-images.githubusercontent.com/760382/109377901-8bdc5180-78ce-11eb-9b7b-f97fd8320cb4.png)
![image](https://user-images.githubusercontent.com/760382/109377904-90a10580-78ce-11eb-875c-cea49fd2cb67.png)

scheint zu funktionieren.

Danke für deine Anleitung.

**Comment by yasars** [comment]
könntest du dies bitte als code hier einsetzte!!! @kotana  danke
