### ISSUE TITLE
Information on your Home assistant Gas consumption

### ISSUE THREAD

**Issue by pljda** [saruter/smarthome#3]
Hi there,
I have found your settings with regards to gas metering. Thanks a lot. It works. (I also have BK-G6 but with the In-Z62 sensor and still need too find the coorect coefficiency.
I was wondering if you could share your HA setting with the daily, weeky, monthly consumption in M3 & kWh.

thank you

philippe

**Comment by saruter** [comment]
Hi, I added the config for the utility_meter integration in the [docs](https://smarthome.ms1.de/projekte/gasverbrauch/). I only store the values in m^3 in Home Assistant. For converting the values in € in Grafana I use some formula which is dependent on your type of gas (which energy is stored in one m^3 and in my case some other values I could look up in my bills of my local gas supplier)
