### ISSUE TITLE
Stromzähler

### ISSUE THREAD

**Issue by polo1860** [saruter/smarthome#4]
Hallo, danke für die gute Darstellung deiner Projekte.
Ich habe zum Stromzähler eine Frage.
Woher kommt die 6 bei - multiply ?
Ich habe einen anderen Stromzähler wie du und muss das deshalb vermutlich anpassen. Meine Pulsrate liegt bei 1000 und nicht bei 10000.

**Comment by polo1860** [comment]
Ich glaube, dass ich es jetzt verstanden habe. In deinem Beispiel ist es so das 1 Impuls pro Sekunde 360 W bedeutet. In meinem Fall sind 3600 W. Heißt mein Multiplikator ist dann 60.

**Comment by yasars** [comment]
moin nutze dieses projekt für meinen ferries stromzähler ... muss ich da als multiply 7.5 eingeben? weil mein zähler mach 75 u/ für 1 kwh.... danke
